FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    g++ \
    default-jdk \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY . /app

RUN pip install --no-cache-dir \
    redis \
    pydantic \
    fastapi \
    uvicorn \
    stripe \
    razorpay \
    requests \
    google-genai

CMD ["python", "-m", "packages.worker.src.main"]
