import type { editor } from 'monaco-editor';

export const LINEAR_MIDNIGHT_THEME_NAME = 'linear-midnight';

export const LINEAR_MIDNIGHT_THEME: editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: '', foreground: 'd4d4d4' },
    { token: 'comment', foreground: '6a9955', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'c586c0' },
    { token: 'keyword.control', foreground: 'c586c0' },
    { token: 'keyword.operator', foreground: 'd4d4d4' },
    { token: 'keyword.directive', foreground: 'c586c0' },
    { token: 'keyword.directive.include', foreground: 'c586c0' },
    { token: 'type', foreground: '4ec9b0' },
    { token: 'type.identifier', foreground: '4ec9b0' },
    { token: 'type.primitive', foreground: '569cd6' },
    { token: 'storage.type', foreground: '569cd6' },
    { token: 'storage.modifier', foreground: '569cd6' },
    { token: 'identifier', foreground: '9cdcfe' },
    { token: 'variable', foreground: '9cdcfe' },
    { token: 'variable.parameter', foreground: '9cdcfe' },
    { token: 'variable.name', foreground: '9cdcfe' },
    { token: 'function', foreground: 'dcdcaa' },
    { token: 'entity.name.function', foreground: 'dcdcaa' },
    { token: 'support.function', foreground: 'dcdcaa' },
    { token: 'string', foreground: 'ce9178' },
    { token: 'string.escape', foreground: 'd7ba7d' },
    { token: 'number', foreground: 'b5cea8' },
    { token: 'number.hex', foreground: 'b5cea8' },
    { token: 'delimiter', foreground: 'd4d4d4' },
    { token: 'delimiter.bracket', foreground: 'ffd700' },
    { token: 'delimiter.parenthesis', foreground: 'da70d6' },
  ],
  colors: {
    'editor.background': '#0b0c0e',
    'editor.foreground': '#d4d4d4',
    'editor.lineHighlightBackground': '#16181d',
    'editor.selectionBackground': '#264f7866',
    'editor.inactiveSelectionBackground': '#3a3d4140',
    'editorCursor.foreground': '#e4f222',
    'editorLineNumber.foreground': '#495162',
    'editorLineNumber.activeForeground': '#c6c6c6',
    'editorIndentGuide.background': '#23252a',
    'editorIndentGuide.activeBackground': '#383b3f',
    'scrollbarSlider.background': '#23252a80',
    'scrollbarSlider.hoverBackground': '#383b3f',
    'scrollbarSlider.activeBackground': '#4a4d55',
  },
};
