import type { editor } from 'monaco-editor';

export const LINEAR_MIDNIGHT_THEME_NAME = 'linear-midnight';

export const LINEAR_MIDNIGHT_THEME: editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: '', foreground: 'f7f8f8', background: '08090a' },
    { token: 'comment', foreground: '575a61', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'f7f8f8', fontStyle: 'bold' },
    { token: 'keyword.control', foreground: 'f7f8f8', fontStyle: 'bold' },
    { token: 'operator', foreground: '8a8f98' },
    { token: 'string', foreground: '27a644' },
    { token: 'string.escape', foreground: '27a644' },
    { token: 'number', foreground: 'f59e0b' },
    { token: 'type', foreground: '8a8f98' },
    { token: 'type.identifier', foreground: '8a8f98' },
    { token: 'function', foreground: 'f7f8f8' },
    { token: 'identifier', foreground: 'f7f8f8' },
    { token: 'delimiter', foreground: '8a8f98' },
    { token: 'tag', foreground: 'eb5757' },
  ],
  colors: {
    'editor.background': '#08090a',
    'editor.foreground': '#f7f8f8',
    'editorLineNumber.foreground': '#575a61',
    'editorLineNumber.activeForeground': '#f7f8f8',
    'editorCursor.foreground': '#e4f222',
    'editor.lineHighlightBackground': '#0f1011',
    'editor.selectionBackground': '#23252a',
    'editor.inactiveSelectionBackground': '#1a1b1e',
    'editorIndentGuide.background1': 'rgba(255, 255, 255, 0.05)',
    'editorIndentGuide.activeBackground1': '#383b3f',
    'editorWhitespace.foreground': 'rgba(255, 255, 255, 0.06)',
    'editorGutter.background': '#08090a',
    'scrollbarSlider.background': 'rgba(255, 255, 255, 0.08)',
    'scrollbarSlider.hoverBackground': 'rgba(255, 255, 255, 0.16)',
    'scrollbarSlider.activeBackground': '#383b3f',
    'editorWidget.background': '#0f1011',
    'editorWidget.border': 'rgba(255, 255, 255, 0.1)',
    'editorSuggestWidget.background': '#0f1011',
    'editorSuggestWidget.border': 'rgba(255, 255, 255, 0.1)',
    'editorSuggestWidget.selectedBackground': '#1c1d1f',
    'editorSuggestWidget.highlightForeground': '#f7f8f8',
  },
};
